apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-myapp
  template:
    metadata:
      labels:
        app: demo-myapp
    spec:
      containers:
      - name: demo-myapp
        image: demo-myapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000